version: '3.7'

services:
  sensei_next_db:
    image: 'postgres:10.5'
    container_name: sensei_next_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #   - 5432:5432
    restart: always

  sensei_next:
    container_name: sensei_next
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./node_modules
      - .:/app
    environment:
      - APP_DB_TYPE=postgres
      - APP_DB_HOST=sensei_next_db
      - APP_DB_PORT=5432
      - APP_DB_DB=sensei_next_dev
      - APP_DB_USER=dev_user
      - APP_DB_PASSWORD=123test
      - JWT_SECRET=dsf21124j32h487232344fds
      - JWT_EXPIRES_IN=1d
      - NODE_ENV=development
      - APP_PORT=3000
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - sensei_next_db